"""M7: backend API, persistence, reports and security boundaries.

Every test here drives the real application over the real engine: uploads are
real captures, analyses run the real pipeline, and exports are generated by the
real renderers. Nothing about the forensic result is mocked, because a test of
an adapter that fakes what it adapts proves nothing.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from securemailscope.backend.app import AppState, create_app
from securemailscope.backend.database import CaptureRow, Database, JobRow
from securemailscope.backend.security import TOKEN_HEADER
from securemailscope.backend.storage import CaptureStorage, UploadRejected
from tests.narrowing import present

pytestmark = pytest.mark.filterwarnings("ignore")

FIXTURES = Path(__file__).parent / "fixtures" / "generated"


@pytest.fixture
def state(tmp_path: Path):
    app_state = AppState(tmp_path / "app")
    yield app_state
    app_state.shutdown()


@pytest.fixture
def client(state: AppState):
    # base_url must present a permitted Host: the guard refuses anything else,
    # which is the DNS-rebinding defence and is asserted separately below.
    with TestClient(create_app(state), base_url="http://127.0.0.1") as test_client:
        test_client.headers.update({TOKEN_HEADER: state.token.value})
        yield test_client


def upload(client: TestClient, name: str) -> dict:
    data = (FIXTURES / name).read_bytes()
    response = client.post(
        "/api/captures", files={"file": (name, data, "application/octet-stream")}
    )
    assert response.status_code == 200, response.text
    return response.json()


def analyse(client: TestClient, state: AppState, capture_ids: list[str]) -> dict:
    investigation = client.post(
        "/api/investigations", json={"name": "Test", "capture_ids": capture_ids}
    ).json()
    client.post(f"/api/investigations/{investigation['investigation_id']}/analyze")
    state.service.wait(investigation["investigation_id"])
    return client.get(f"/api/investigations/{investigation['investigation_id']}").json()


# ---------------------------------------------------------------------------
# Health and security boundaries
# ---------------------------------------------------------------------------
def test_health_reports_real_versions(client: TestClient) -> None:
    body = client.get("/api/health").json()
    assert body["status"] == "ok"
    assert body["report_schema_version"] == "1.4.0"
    assert body["database_schema_version"] >= 1
    assert body["analyzer_works_without_ml"] is True


def test_a_foreign_host_header_is_refused(state: AppState) -> None:
    """DNS rebinding reaches the socket but carries the attacker's hostname."""
    with TestClient(create_app(state), base_url="http://attacker.example.com") as bad:
        response = bad.get("/api/health")
    assert response.status_code == 400
    assert response.json()["error"] == "host_not_allowed"


def test_requests_without_a_token_are_refused(state: AppState) -> None:
    with TestClient(create_app(state), base_url="http://127.0.0.1") as anonymous:
        assert anonymous.get("/api/investigations").status_code == 401
        # Health stays open so a client can bootstrap.
        assert anonymous.get("/api/health").status_code == 200


def test_a_wrong_token_is_refused(state: AppState) -> None:
    with TestClient(create_app(state), base_url="http://127.0.0.1") as bad:
        response = bad.get(
            "/api/investigations", headers={TOKEN_HEADER: "not-the-token"}
        )
    assert response.status_code == 401


def test_cors_is_not_permissive(state: AppState) -> None:
    from securemailscope.backend.security import allowed_origins

    origins = allowed_origins()
    assert "*" not in origins
    assert all(
        o.startswith("http://127.0.0.1") or o.startswith("http://localhost")
        for o in origins
    )

    with TestClient(create_app(state), base_url="http://127.0.0.1") as test_client:
        response = test_client.get(
            "/api/health", headers={"origin": "http://evil.example.com"}
        )
    assert "access-control-allow-origin" not in {k.lower() for k in response.headers}


def test_responses_carry_hardening_headers(client: TestClient) -> None:
    headers = client.get("/api/health").headers
    assert headers["x-content-type-options"] == "nosniff"
    assert headers["x-frame-options"] == "DENY"
    assert "default-src 'none'" in headers["content-security-policy"]


def test_an_error_body_does_not_leak_internals(client: TestClient) -> None:
    response = client.get("/api/investigations/inv-does-not-exist")
    assert response.status_code == 404
    body = json.dumps(response.json())
    for leak in ("Traceback", "/Users/", "/Volumes/", "sqlalchemy", "sqlite3"):
        assert leak not in body


# ---------------------------------------------------------------------------
# Upload validation
# ---------------------------------------------------------------------------
def test_a_real_capture_uploads_and_is_identified_by_content(client: TestClient) -> None:
    body = upload(client, "aa_tls10_static_rsa.pcap")
    assert body["file_format"] == "PCAP"
    assert body["capture_id"].startswith("sha256:")
    # The same bytes under another name are the same evidence, not a new row.
    again = upload(client, "aa_tls10_static_rsa.pcap")
    assert again["capture_id"] == body["capture_id"]
    assert client.get("/api/captures").json()["total"] == 1


def test_a_pcapng_capture_uploads(client: TestClient) -> None:
    body = upload(client, "k_pcapng_nanosecond.pcapng")
    assert body["file_format"] == "PCAPNG"


def test_a_file_that_is_not_a_capture_is_rejected(client: TestClient) -> None:
    """The extension is not trusted; the magic bytes decide."""
    payload = b"<html>not a capture</html>" * 20
    response = client.post(
        "/api/captures",
        files={"file": ("malicious.pcap", payload, "application/octet-stream")},
    )
    assert response.status_code == 422
    assert "not a pcap or pcapng capture" in response.json()["detail"]


def test_an_empty_upload_is_rejected(client: TestClient) -> None:
    response = client.post(
        "/api/captures", files={"file": ("empty.pcap", b"", "application/octet-stream")}
    )
    assert response.status_code == 422


def test_the_upload_limit_is_enforced_while_streaming(tmp_path: Path) -> None:
    """Abandoned mid-write, not measured after the whole file lands on disk."""
    storage = CaptureStorage(tmp_path / "s", max_bytes=1024)
    import io

    payload = b"\xd4\xc3\xb2\xa1" + b"x" * 8192
    with pytest.raises(UploadRejected, match="exceeds the configured limit"):
        storage.store(io.BytesIO(payload), "big.pcap")
    assert list((tmp_path / "s" / "captures").glob("*.bin")) == [], (
        "the partial file must be removed, not left behind"
    )


def test_a_traversing_filename_cannot_escape_storage(tmp_path: Path) -> None:
    import io

    storage = CaptureStorage(tmp_path / "s")
    data = (FIXTURES / "aa_tls10_static_rsa.pcap").read_bytes()
    stored = storage.store(io.BytesIO(data), "../../../../etc/passwd.pcap")
    assert storage.captures.resolve() in stored.path.resolve().parents
    assert "/" not in stored.original_name and ".." not in stored.path.name


def test_storage_is_outside_the_repository(state: AppState) -> None:
    repository = Path(__file__).resolve().parent.parent
    assert repository not in state.storage.root.parents
    assert state.storage.root != repository


# ---------------------------------------------------------------------------
# Analysis execution and persistence
# ---------------------------------------------------------------------------
def test_analysis_runs_the_real_engine_and_persists(client: TestClient, state: AppState) -> None:
    capture = upload(client, "aa_tls10_static_rsa.pcap")
    detail = analyse(client, state, [capture["capture_id"]])
    investigation = detail["investigation"]
    assert investigation["status"] == "COMPLETED"
    assert investigation["session_count"] == 1
    assert investigation["finding_count"] == 4
    # The engine's own numbers, not recomputed anywhere.
    assert investigation["posture_score"] == 59
    assert investigation["score_band"] == "WEAK"
    assert detail["policy_version"] == "1.0.0"


def test_job_progress_is_real(client: TestClient, state: AppState) -> None:
    ids = [upload(client, name)["capture_id"] for name in
           ("aa_tls10_static_rsa.pcap", "t_a_tls12_complete_handshake.pcap")]
    detail = analyse(client, state, ids)
    job = detail["jobs"][0]
    assert job["captures_total"] == 2
    assert job["captures_done"] == 2
    assert job["status"] == "COMPLETED"
    assert job["stage"] == "completed"


def test_a_failed_capture_stays_visible(client: TestClient, state: AppState) -> None:
    """A partial batch failure must not vanish from the aggregate."""
    good = upload(client, "aa_tls10_static_rsa.pcap")["capture_id"]
    # A stored capture whose bytes are later truncated: it passed upload
    # validation but cannot be analysed.
    with state.database.session() as session:
        good_path = present(
            session.get(CaptureRow, good), "the stored capture row"
        ).stored_path
    broken_path = Path(good_path).parent / "deadbeef00000000000000000000beef.bin"
    broken_path.write_bytes(b"\xd4\xc3\xb2\xa1truncated")
    with state.database.session() as session:
        session.add(CaptureRow(
            capture_id="sha256:broken", storage_id="deadbeef00000000000000000000beef",
            original_name="broken.pcap", stored_path=str(broken_path),
            file_size_bytes=13, sha256="sha256:broken", file_format="PCAP",
        ))
    detail = analyse(client, state, [good, "sha256:broken"])
    names = {c["original_name"] for c in detail["captures"]}
    assert "broken.pcap" in names, "the failed capture disappeared from the inventory"


def test_a_duplicate_analysis_is_refused(client: TestClient, state: AppState) -> None:
    capture = upload(client, "aa_tls10_static_rsa.pcap")
    investigation = client.post(
        "/api/investigations", json={"name": "T", "capture_ids": [capture["capture_id"]]}
    ).json()
    identifier = investigation["investigation_id"]
    first = client.post(f"/api/investigations/{identifier}/analyze")
    assert first.status_code == 200
    second = client.post(f"/api/investigations/{identifier}/analyze")
    # Either refused as already running, or the first finished first. Both are
    # correct; what must not happen is two workers writing the same rows.
    assert second.status_code in (200, 409)
    state.service.wait(identifier)


def test_results_survive_a_restart(tmp_path: Path) -> None:
    root = tmp_path / "app"
    first = AppState(root)
    with TestClient(create_app(first), base_url="http://127.0.0.1") as client:
        client.headers.update({TOKEN_HEADER: first.token.value})
        capture = upload(client, "aa_tls10_static_rsa.pcap")
        detail = analyse(client, first, [capture["capture_id"]])
        identifier = detail["investigation"]["investigation_id"]
    first.shutdown()

    # A fresh process over the same directory.
    second = AppState(root)
    try:
        with TestClient(create_app(second), base_url="http://127.0.0.1") as client:
            client.headers.update({TOKEN_HEADER: second.token.value})
            reloaded = client.get(f"/api/investigations/{identifier}").json()
            assert reloaded["investigation"]["finding_count"] == 4
            assert reloaded["investigation"]["posture_score"] == 59
            sessions = client.get(f"/api/investigations/{identifier}/sessions").json()
            assert sessions["total"] == 1
    finally:
        second.shutdown()


def test_an_interrupted_job_is_never_reported_as_completed(tmp_path: Path) -> None:
    database = Database(tmp_path / "db.sqlite3")
    from securemailscope.backend.database import InvestigationRow

    with database.session() as session:
        session.add(InvestigationRow(investigation_id="inv-x", name="x", status="RUNNING"))
        session.add(JobRow(job_id="job-x", investigation_id="inv-x", status="RUNNING"))
    database.close()

    recovered = Database(tmp_path / "db.sqlite3")
    assert recovered.recover_interrupted_jobs() == 1
    with recovered.session() as session:
        job = present(session.get(JobRow, "job-x"), "job-x")
        assert job.status == "FAILED"
        assert "restarted" in (job.error or "")
        assert present(
            session.get(InvestigationRow, "inv-x"), "inv-x"
        ).status == "FAILED"
    recovered.close()


# ---------------------------------------------------------------------------
# Retrieval, filtering, pagination, evidence navigation
# ---------------------------------------------------------------------------
@pytest.fixture
def analysed(client: TestClient, state: AppState):
    ids = [upload(client, name)["capture_id"] for name in
           ("aa_tls10_static_rsa.pcap", "t_a_tls12_complete_handshake.pcap")]
    return analyse(client, state, ids)


def test_sessions_can_be_filtered_and_paginated(client: TestClient, analysed) -> None:
    identifier = analysed["investigation"]["investigation_id"]
    page = client.get(f"/api/investigations/{identifier}/sessions?limit=1").json()
    assert page["total"] == 2
    assert len(page["items"]) == 1
    filtered = client.get(
        f"/api/investigations/{identifier}/sessions?tls_version=TLS%201.0"
    ).json()
    assert filtered["total"] == 1
    assert filtered["items"][0]["tls_version"] == "TLS 1.0"
    searched = client.get(
        f"/api/investigations/{identifier}/sessions?search=AES_128_CBC"
    ).json()
    assert searched["total"] == 1


def test_an_invalid_sort_key_is_rejected(client: TestClient, analysed) -> None:
    identifier = analysed["investigation"]["investigation_id"]
    response = client.get(f"/api/investigations/{identifier}/sessions?sort=DROP+TABLE")
    assert response.status_code == 422


def test_findings_link_to_real_packet_evidence(client: TestClient, analysed) -> None:
    identifier = analysed["investigation"]["investigation_id"]
    findings = client.get(f"/api/investigations/{identifier}/findings").json()
    assert findings["total"] >= 4
    detail = client.get(f"/api/findings/{findings['items'][0]['finding_id']}").json()
    assert detail["evidence"], "a finding must carry its evidence"
    for reference in detail["evidence"]:
        assert reference["packet_number"] >= 1
        assert reference["timestamp"]
        assert reference["source_observation"]
    # And the session it names really exists.
    session = client.get(f"/api/sessions/{detail['finding']['session_id']}")
    assert session.status_code == 200


def test_findings_can_be_filtered_by_severity(client: TestClient, analysed) -> None:
    identifier = analysed["investigation"]["investigation_id"]
    high = client.get(f"/api/investigations/{identifier}/findings?severity=HIGH").json()
    assert high["total"] >= 1
    assert all(f["severity"] == "HIGH" for f in high["items"])


def test_session_detail_contains_no_payload_or_credential(client: TestClient, analysed) -> None:
    identifier = analysed["investigation"]["investigation_id"]
    sessions = client.get(f"/api/investigations/{identifier}/sessions").json()
    detail = client.get(f"/api/sessions/{sessions['items'][0]['session_id']}").json()
    text = json.dumps(detail)
    # Dummy credential material must be absent. The word "payload" appears in
    # explanatory prose ("no application payload was parsed"), which is a
    # description of what was *not* done rather than a leak, so the check is
    # on actual credential strings and on the stream summary's shape.
    for secret in ("NotARealPassword", "dummy-user@example.invalid", "bXlwYXNzd29yZA"):
        assert secret not in text
    streams = detail["detail"]["streams"]["client_to_server"]
    assert "bytes_reconstructed" in streams, "counts must be present"
    for leaky in ("data", "content", "bytes", "hex", "preview"):
        assert leaky not in streams, f"the stream summary must not carry {leaky!r}"


def test_intelligence_and_timeline_are_served(client: TestClient, analysed) -> None:
    identifier = analysed["investigation"]["investigation_id"]
    fingerprints = client.get(
        f"/api/investigations/{identifier}/intelligence?section=fingerprints"
    ).json()
    assert len(fingerprints["items"]) == 2
    timeline = client.get(f"/api/investigations/{identifier}/timeline").json()
    assert timeline["total"] > 0
    assert timeline["items"][0]["order_index"] == 0
    filtered = client.get(
        f"/api/investigations/{identifier}/timeline?event_type=CLIENT_HELLO"
    ).json()
    assert all(e["event_type"] == "CLIENT_HELLO" for e in filtered["items"])


def test_ml_results_preserve_m6_distinctions(client: TestClient, analysed) -> None:
    identifier = analysed["investigation"]["investigation_id"]
    body = client.get(f"/api/investigations/{identifier}/ml").json()
    summary = body["summary"]
    assert summary["anomaly_algorithm"] == "rarity_baseline"
    assert summary["anomaly_detector_is_ml"] is False, (
        "the selected detector is a frequency table and must not be labelled ML"
    )
    assert summary["classification_validation_status"] == "NOT_VALIDATED"
    # Benchmarks come from the versioned evaluation artifact, not the UI.
    assert body["evaluation"]["anomaly_selection"]["selected"] == "rarity_baseline"


def test_settings_are_validated(client: TestClient) -> None:
    assert client.post("/api/settings", json={"max_packets": -1}).status_code == 422
    assert client.post("/api/settings", json={"enable_ml": "yes"}).status_code == 422
    assert client.post(
        "/api/settings", json={"default_report_format": "docx"}
    ).status_code == 422
    updated = client.post("/api/settings", json={"enable_ml": False}).json()
    assert updated["enable_ml"] is False
    assert "enable_ml" in updated["requires_reanalysis"]


def test_deleting_a_capture_removes_the_file_but_keeps_results(
    client: TestClient, state: AppState
) -> None:
    capture = upload(client, "aa_tls10_static_rsa.pcap")
    detail = analyse(client, state, [capture["capture_id"]])
    identifier = detail["investigation"]["investigation_id"]
    with state.database.session() as session:
        path = Path(
            present(
                session.get(CaptureRow, capture["capture_id"]),
                "the stored capture row",
            ).stored_path
        )
    assert path.is_file()

    response = client.delete(f"/api/captures/{capture['capture_id']}")
    assert response.status_code == 200
    assert response.json()["file_removed"] is True
    assert not path.exists()
    # The investigation is not silently discarded.
    assert client.get(f"/api/investigations/{identifier}").json()[
        "investigation"
    ]["finding_count"] == 4


# ---------------------------------------------------------------------------
# Exports and report parity
# ---------------------------------------------------------------------------
def test_all_three_formats_export(client: TestClient, analysed) -> None:
    identifier = analysed["investigation"]["investigation_id"]
    formats = (
        ("json", "application/json"),
        ("html", "text/html"),
        ("pdf", "application/pdf"),
    )
    for fmt, media in formats:
        response = client.get(f"/api/investigations/{identifier}/export/{fmt}")
        assert response.status_code == 200, fmt
        assert media in response.headers["content-type"]
        assert len(response.content) > 500
        assert "attachment" in response.headers["content-disposition"]


def test_exporting_an_unanalysed_investigation_is_refused(client: TestClient) -> None:
    capture = upload(client, "aa_tls10_static_rsa.pcap")
    investigation = client.post(
        "/api/investigations", json={"name": "T", "capture_ids": [capture["capture_id"]]}
    ).json()
    response = client.get(
        f"/api/investigations/{investigation['investigation_id']}/export/json"
    )
    assert response.status_code == 409
    assert "no analysed captures" in response.json()["detail"]


def test_an_unknown_export_format_is_refused(client: TestClient, analysed) -> None:
    identifier = analysed["investigation"]["investigation_id"]
    assert client.get(
        f"/api/investigations/{identifier}/export/docx"
    ).status_code == 422


def test_the_html_report_is_standalone(client: TestClient, analysed, tmp_path: Path) -> None:
    from securemailscope.reporting.html_report import find_external_references

    identifier = analysed["investigation"]["investigation_id"]
    html = client.get(f"/api/investigations/{identifier}/export/html").text
    assert find_external_references(html) == []
    for scheme in ("http://", "https://"):
        # A URL in prose is fine; a fetchable reference is not, which
        # find_external_references already checked.
        assert f'src="{scheme}' not in html
        assert f'href="{scheme}' not in html


def test_the_html_report_escapes_untrusted_text() -> None:
    """Capture-derived text is untrusted and must never become markup."""
    from securemailscope.pipeline import analyze_capture
    from securemailscope.reporting.html_report import render_html
    from securemailscope.reporting.report_model import build_report

    result = analyze_capture(FIXTURES / "aa_tls10_static_rsa.pcap")
    model = build_report([result], title='<script>alert("xss")</script>')
    html = render_html(model)
    assert "<script>alert" not in html
    assert "&lt;script&gt;" in html


def test_reports_contain_no_payload_or_credentials(client: TestClient, state: AppState) -> None:
    capture = upload(client, "p_m_auth_before_tls.pcap")
    detail = analyse(client, state, [capture["capture_id"]])
    identifier = detail["investigation"]["investigation_id"]

    from securemailscope.testing.fixtures import build_fixtures

    spec = next(s for s in build_fixtures() if s.name == "P_M_auth_before_tls")
    assert spec.forbidden_strings

    for fmt in ("json", "html"):
        body = client.get(f"/api/investigations/{identifier}/export/{fmt}").text
        for secret in spec.forbidden_strings:
            assert secret not in body, f"{secret!r} leaked into the {fmt} report"

    pdf_bytes = client.get(f"/api/investigations/{identifier}/export/pdf").content
    import io

    from pypdf import PdfReader

    text = "\n".join(page.extract_text() for page in PdfReader(io.BytesIO(pdf_bytes)).pages)
    for secret in spec.forbidden_strings:
        assert secret not in text, f"{secret!r} leaked into the PDF"


def test_all_three_formats_agree_on_the_facts(client: TestClient, analysed) -> None:
    """§20 report parity, checked field by field."""
    import io

    from pypdf import PdfReader

    identifier = analysed["investigation"]["investigation_id"]
    document = client.get(f"/api/investigations/{identifier}/export/json").json()
    html = client.get(f"/api/investigations/{identifier}/export/html").text
    pdf = PdfReader(io.BytesIO(client.get(f"/api/investigations/{identifier}/export/pdf").content))
    pdf_text = "\n".join(page.extract_text() for page in pdf.pages)
    # Long identifiers wrap across lines in the PDF, which is correct: wrapping
    # is what stops them being clipped. Comparison is therefore on text with
    # whitespace removed.
    pdf_flat = "".join(pdf_text.split())
    html_flat = "".join(html.split())

    # Capture ids
    for capture in document["captures"]:
        assert capture["capture_id"] in html_flat
        assert capture["capture_id"] in pdf_flat

    # Session count
    assert len(document["sessions"]) == 2
    for session in document["sessions"]:
        assert session["session_id"] in html_flat
        assert session["session_id"] in pdf_flat

    # Finding ids, severities and rule ids
    for finding in document["findings"]:
        assert finding["rule_id"] in html_flat
        assert finding["rule_id"] in pdf_flat
        assert finding["severity"] in html_flat

    # Policy version, score and coverage
    posture = document["posture"]
    assert document["policy_version"] in html_flat
    assert document["policy_version"] in pdf_flat
    if posture["score"] is not None:
        assert str(posture["score"]) in html_flat
        assert f"{posture['score']}/100" in pdf_flat

    # Remediation ids
    for remediation in document["remediations"]:
        assert remediation["remediation_id"] in html_flat
        assert remediation["remediation_id"] in pdf_flat

    # Blast-radius counts
    for radius in document["blast_radius"]:
        assert radius["subject"] in html_flat
        assert radius["subject"] in pdf_flat

    # ML validation status
    assert document["ml"]["classification_validation_status"] in html_flat
    assert document["ml"]["classification_validation_status"] in pdf_flat
    assert document["ml"]["anomaly_algorithm"] in html_flat
    assert document["ml"]["anomaly_algorithm"] in pdf_flat


def test_the_pdf_renders_correctly(client: TestClient, analysed, tmp_path: Path) -> None:
    """§19: not merely produced — rendered and inspected."""
    import io

    import numpy as np
    import pypdfium2 as pdfium
    from pypdf import PdfReader

    identifier = analysed["investigation"]["investigation_id"]
    data = client.get(f"/api/investigations/{identifier}/export/pdf").content
    path = tmp_path / "report.pdf"
    path.write_bytes(data)

    reader = PdfReader(io.BytesIO(data))
    assert len(reader.pages) >= 2
    # A4 at 72dpi is 595 x 842 points.
    box = reader.pages[0].mediabox
    assert abs(float(box.width) - 595) < 2
    assert abs(float(box.height) - 842) < 2

    text = "\n".join(page.extract_text() for page in reader.pages)
    assert "Executive summary" in text
    assert "Security findings" in text
    assert "Limitations" in text
    assert "Page 1" in text
    assert "Observed within analyzed captures only" in text

    document = pdfium.PdfDocument(path)
    assert len(document) == len(reader.pages)
    for index, page in enumerate(document):
        image = page.render(scale=2).to_pil().convert("L")
        array = np.asarray(image)
        ink = (array < 200).mean()
        assert ink > 0.002, f"page {index + 1} is blank"
        # Nothing may bleed into the margins: that is what clipping looks like.
        assert (array[:, -28:] < 200).mean() < 0.0005, f"page {index + 1} clips on the right"
        assert (array[:24, :] < 200).mean() < 0.0005, f"page {index + 1} clips at the top"


def test_long_values_wrap_rather_than_clipping(client: TestClient, analysed) -> None:
    """A capture id is 71 characters and must not be truncated silently."""
    import io

    from pypdf import PdfReader

    identifier = analysed["investigation"]["investigation_id"]
    data = client.get(f"/api/investigations/{identifier}/export/pdf").content
    text = "\n".join(page.extract_text() for page in PdfReader(io.BytesIO(data)).pages)
    normalised = text.replace("\n", "").replace(" ", "")
    document = client.get(f"/api/investigations/{identifier}/export/json").json()
    for capture in document["captures"]:
        assert capture["capture_id"].replace(" ", "") in normalised, (
            "a full capture identifier was clipped in the PDF"
        )
