#!/usr/bin/env python3
"""Generate the policy and remediation documents from the code that implements them.

``docs/security-policy.md`` and ``docs/remediation-catalog.md`` describe every
rule, weight, threshold and corrective action. Written by hand they would drift
from the catalogue within a milestone, and a policy document that disagrees
with the engine is worse than none: a reader would check the wrong thresholds.

Both files are committed, so a reviewer reads them without running anything.
Re-run this script after changing the policy or catalogue; the test suite
asserts the committed files match what the script produces.
"""

from __future__ import annotations

import sys
from io import StringIO
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from securemailscope.assessment.catalog import REMEDIATIONS, RULES  # noqa: E402
from securemailscope.assessment.policy import (  # noqa: E402
    APPROVED_ENCRYPTION,
    DEFAULT_POLICY,
    PROHIBITED_ENCRYPTION,
    SEVERITY_WEIGHTS,
    THRESHOLD_RATIONALE,
)

BANNER = (
    "<!-- Generated by scripts/generate_policy_docs.py. Do not edit by hand; "
    "edit the policy or catalogue and re-run. -->"
)


def security_policy() -> str:
    out = StringIO()
    p = lambda *a: print(*a, file=out)  # noqa: E731

    p(BANNER)
    p()
    p("# Security policy")
    p()
    p(
        f"**Policy id:** `{DEFAULT_POLICY.policy_id}` &nbsp;&nbsp; "
        f"**Version:** `{DEFAULT_POLICY.policy_version}` &nbsp;&nbsp; "
        f"**Published:** {DEFAULT_POLICY.published}"
    )
    p()
    p("""This document is the human-readable form of the policy the assessment
engine applies.

A policy is a set of **choices**, not a set of forensic facts. Changing it
changes the judgement and never the observations: the reconstructed sessions,
handshakes and certificates in a report are identical whatever policy was
applied. That separation is the point of having a named, versioned policy at
all -- a reader who disagrees with a threshold can see exactly which one,
change it, and re-run against the same evidence.

## What the outcomes mean

| Outcome | Meaning |
| --- | --- |
| `FAIL` | The condition the rule tests for **was observed**. |
| `PASS` | Enough evidence was present to evaluate the condition, and it held. |
| `UNKNOWN` | The rule applies, but the capture does not contain what it needs. |
| `NOT_APPLICABLE` | The rule does not apply to this session at all. |

`UNKNOWN` is load-bearing and is never promoted to `PASS`. A capture that does
not show a certificate chain has not shown a *good* chain; it has shown
nothing. Only `FAIL` results become findings, so an unavailable observation
never produces one.

## Severity, confidence and priority are three axes

**Severity** is how bad the condition is under this policy. **Confidence** is
how sure we are the condition was observed. **Priority** is the ordering that
follows from both, plus any operator-supplied asset criticality.

They are never multiplied together. A `CRITICAL` finding seen with `LOW`
confidence stays `CRITICAL`; multiplying it by a confidence percentage would
quietly turn it into something that reads like a `MEDIUM`, presenting a
judgement about evidence quality as though it were a judgement about severity.
Priority comes from a lookup table, reproduced in
[scoring-methodology.md](scoring-methodology.md).
""")

    p("## Thresholds and why they are what they are")
    p()
    for key, text in THRESHOLD_RATIONALE.items():
        p(f"**`{key}`** -- {text}")
        p()

    p("## Cipher policy")
    p()
    p("### Algorithms this policy will not accept")
    p()
    p("Each prohibited algorithm is owned by exactly **one** rule. Ownership is")
    p("what stops a single misconfigured setting being reported three times at")
    p("three severities.")
    p()
    p("| Algorithm | Reason | Reported by |")
    p("| --- | --- | --- |")
    for name, (reason, owner) in PROHIBITED_ENCRYPTION.items():
        p(f"| `{name}` | {reason} | `{owner}` |")
    p()
    p("### Algorithms this policy approves")
    p()
    p(", ".join(f"`{name}`" for name in sorted(APPROVED_ENCRYPTION)))
    p()
    p("""All five are AEAD constructions. CBC-mode suites are **not** prohibited --
they are reported at `MEDIUM` under `TLS-CIPHER-005` as "not on the approved
list", because RFC 9325 §4.2 recommends AEAD rather than forbidding CBC. The
distinction between a prohibition and a recommendation is preserved
deliberately: see *Citation kinds* below.
""")

    p("## Severity weights")
    p()
    p("| Severity | Weight |")
    p("| --- | --- |")
    for severity, weight in SEVERITY_WEIGHTS.items():
        p(f"| {severity.value} | {weight:.0f} |")
    p()
    p("""These are **project-defined ordering judgements, not validated industry
benchmarks**. They were chosen so that one `CRITICAL` control outweighs three
`MEDIUM` ones, and so `INFO` contributes nothing to the score while remaining
reportable. Every one is configurable, and any change an operator makes is
recorded in the report's policy block and changes the policy fingerprint.
""")

    p("## Citation kinds")
    p()
    p("""Every standards reference carries a `kind`, because conflating the three
is how "NIST says you must" claims get made about things NIST merely
recommends:

| Kind | Meaning |
| --- | --- |
| `PROTOCOL_REQUIREMENT` | The cited document requires this of conforming implementations. |
| `STANDARDS_RECOMMENDATION` | The cited document recommends it for general use. |
| `PROJECT_POLICY` | This project's own choice, cited as such. |
| `ENVIRONMENT_CHOICE` | Depends on the deployment; the operator decides. |
""")

    p("## The rules")
    p()
    p("| Rule | Name | Category | Severity | Weight | De-duplication group | Standards |")
    p("| --- | --- | --- | --- | --- | --- | --- |")
    for rule_id, rule in RULES.items():
        refs = "; ".join(
            reference.document + (f" §{reference.section}" if reference.section else "")
            for reference in rule.standards_references
        )
        p(
            f"| `{rule_id}` | {rule.name} | {rule.category.value} | "
            f"{rule.severity.value} | {SEVERITY_WEIGHTS[rule.severity]:.0f} | "
            f"`{rule.dedup_group}` | {refs} |"
        )
    p()
    p("""Rules sharing a **de-duplication group** describe one underlying weakness.
Scoring counts the group once and reports it once, charging the most severe
member that failed. A NULL-cipher session is therefore not penalised separately
for also being off the approved list.
""")

    p("## Rule detail")
    p()
    for rule_id, rule in RULES.items():
        p(f"### `{rule_id}` -- {rule.name}")
        p()
        p(rule.description)
        p()
        p(f"- **Applies when:** {rule.applicable_when}")
        p(f"- **Requires:** {', '.join(f'`{e}`' for e in rule.required_evidence)}")
        p(f"- **Technical impact:** {rule.technical_impact}")
        if rule.remediation_ids:
            p(
                "- **Remediation:** "
                + ", ".join(f"`{x}`" for x in rule.remediation_ids)
            )
        for reference in rule.standards_references:
            section = f" §{reference.section}" if reference.section else ""
            p(
                f"- **{reference.kind}:** {reference.document}{section} -- "
                f"{reference.title} ({reference.published})"
            )
        p()

    p("## Limitations of this policy")
    p()
    for line in DEFAULT_POLICY.info(None).limitations:
        p(f"- {line}")
    p()
    p("""See [limitations.md](limitations.md) for the limitations of the system as
a whole, and [scoring-methodology.md](scoring-methodology.md) for what the
posture score does and does not mean.
""")
    return out.getvalue()


def remediation_catalog() -> str:
    out = StringIO()
    p = lambda *a: print(*a, file=out)  # noqa: E731

    p(BANNER)
    p()
    p("# Remediation catalogue")
    p()
    p("""Each entry below is offered only when a finding that references it was
actually raised. Advice is never produced for a rule that *might* have failed,
and never for a rule that returned `UNKNOWN`: an operator who acts on advice
for a weakness that was never observed has been sent to fix nothing.

Every entry is vendor-neutral. SecureMailScope does not know what software
produced the traffic it analysed -- a ServerHello names a cipher suite, not a
product -- so naming one would be a guess presented as instruction.

**Nothing here is applied automatically.** The tool is passive: it never
connects to a captured host, never changes a configuration, and never predicts
what a score would become afterwards. A before-and-after comparison is obtained
by fixing the configuration and capturing again.
""")

    p("## Index")
    p()
    p("| Remediation | Title | Raised by |")
    p("| --- | --- | --- |")
    for remediation_id, item in REMEDIATIONS.items():
        rules = ", ".join(f"`{r}`" for r in item.related_rule_ids)
        p(f"| `{remediation_id}` | {item.title} | {rules} |")
    p()

    for remediation_id, item in REMEDIATIONS.items():
        p(f"## `{remediation_id}` -- {item.title}")
        p()
        p(f"**Raised by:** {', '.join(f'`{r}`' for r in item.related_rule_ids)}")
        p()
        p("### Why it matters")
        p()
        p(item.technical_explanation)
        p()
        p("### Recommended action")
        p()
        p(item.recommended_action)
        p()
        p("### Expected effect")
        p()
        p(item.expected_security_effect)
        p()
        p("### Operational considerations")
        p()
        p(item.operational_considerations)
        p()
        p("### How to verify the fix")
        p()
        for step in item.validation_steps:
            p(f"1. {step}")
        p()
        if item.standards_references:
            p("### References")
            p()
            for reference in item.standards_references:
                section = f" §{reference.section}" if reference.section else ""
                p(
                    f"- **{reference.kind}:** {reference.document}{section} -- "
                    f"{reference.title} ({reference.published})"
                )
            p()
    return out.getvalue()


DOCUMENTS = {
    "docs/security-policy.md": security_policy,
    "docs/remediation-catalog.md": remediation_catalog,
}


def main(argv: list[str] | None = None) -> int:
    check = bool(argv) and "--check" in argv
    failures = []
    for relative, build in DOCUMENTS.items():
        path = REPO / relative
        content = build()
        if check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != content:
                failures.append(relative)
            continue
        path.write_text(content, encoding="utf-8")
        print(f"{relative}: {len(content.splitlines())} lines")
    if failures:
        print("out of date (re-run scripts/generate_policy_docs.py):", *failures)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
